### ISSUE TITLE
Ability to show labels on charts

### ISSUE THREAD

**Issue by erik-heintare** [groodlooker/vega-lite#11]
First of all thanks for all the awesome work!

I really like the VEGA custom visualizations, but currently there is no way to show labels on charts.

It should be rather easy to add. One example with labels - https://vega.github.io/vega-lite/examples/layer_bar_labels.html

Thanks again!

**Comment by groodlooker** [comment]
Hi @erikhhhh, one of the hurdles with labels is actually the custom viz UI. It is pretty limiting in terms of how you can organize the configurations - Once I add labels people will also expect ability to customize font, orientation, position, size, color, etc and I am running out of space in the UI! It is something I'm thinking about, you can expect basic label support in next couple weeks.
