### ISSUE TITLE
Labels containing white space cause an Uncaught Error

### ISSUE THREAD

**Issue by tpakeman** [groodlooker/vega-lite#15]
Plotting a measure with a label that contains a newline character (This is a newline in the LookML, presumably \n) causes the Vega viz to break.

There is at least one real world application for this, which is using liquid to format the labels.
For readibility, these are often formatted like this (note the newline after the first if block)
```
label: "{% if param._parameter_value == 'Yes' %}Gross Margin (GBP)
    {% else %}Gross Margin (GBP)
{% endif %}"
```

Here is the stack trace:

[newline_bug_console_log.txt](https://github.com/groodlooker/vega-lite/files/2829123/newline_bug_console_log.txt)

**Comment by groodlooker** [comment]
Hey @tpakeman, try it out again with the new dependencies (new versions of Vega), the links in the readme list all the latest versions, it looks like that should take care of this issue.
