### ISSUE TITLE
Chart sizing issues in looker

### ISSUE THREAD

**Issue by mswilson4040** [groodlooker/vega-lite#17]
The charts are a little too big in looker and are causing scrolling issues.

![2019-05-07_11-22-35](https://user-images.githubusercontent.com/19480392/57323524-ca31cc80-70ba-11e9-86ae-618ce552300b.gif)

The issue seems to be that the logic to fix the sizing in the `spec` property doesn't account for the legend or axis.

I think a couple of minor adjustments resolves this:

1. Use svg instead of canvas. SVG is a little easier to size than a canvas element and is also called out as a potential sizing fix by one of the maintainers [here](https://github.com/vega/vega/issues/691#issuecomment-270470144)
2. Implement a function to fix the sizing of the svg after the chart has been rendered. Basically, get the looker container `div#vis` so we can grab the `clientHeight`/`clientWidth` then update the `svg` with the same dimensions after it's rendered.

**Comment by groodlooker** [comment]
Thanks for the help @mswilson4040! I have incorporated your change into vega 3-2. I made a slight modification where a user can toggle your function on or off under the "Autosize" config option in the advanced section. I found that the constant resizing is a bit distracting while in explore mode, so this way you can toggle it on when ready to add visual to a dashboard. Let me know your thoughts.
