### ISSUE TITLE
Sorting capabilities for legends

### ISSUE THREAD

**Issue by chasec** [groodlooker/vega-lite#8]
Unless I missed it, I don't see capabilities to leverage the sorting capabilities inside Looker - this would be a nice feature to have. Documentation lives here: https://vega.github.io/vega-lite/docs/sort.html

**Comment by groodlooker** [comment]
Hi @chasec,
I added the sorting capability as well as the ordering capability (#9 ), which allows to sort a stacked bar chart. Note that vega-lite does not appear to have support for sub-sorting, however, so it's not perfect when there are multiple facets to a view.  

FYI also added ability to highlight based on a dimension.
